security:
  oauth2:
    client:
      clientId: 360680058434-193adel6skjmkk6jpqmia7iif5marh4g.apps.googleusercontent.com
      clientSecret: bGedYdgHZDSRhBnnrw2QVTI9
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false